import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { NextUIProvider } from "./components/providers/nextUiProvider";

const roboto = Poppins({
  subsets: ["latin"],
  weight: ["100", "400", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "John Rod Dondoyano | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <NextUIProvider>{children}</NextUIProvider>
      </body>
    </html>
  );
}
